# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=24, verbose_name='Марка')),
                ('model', models.CharField(max_length=24, verbose_name='Модель')),
                ('vincode', models.IntegerField(blank=True, null=True, verbose_name='VIN код')),
                ('Agestart', models.DateTimeField(blank=True, null=True, verbose_name='Дата с')),
                ('ctc', models.CharField(max_length=24, verbose_name='CTC')),
                ('number', models.CharField(max_length=24, verbose_name='Гос Номер')),
                ('inwork', models.DateTimeField(blank=True, null=True, verbose_name='В работе с')),
                ('active', models.BooleanField(verbose_name='В работе')),
                ('datacreate', models.DateTimeField(blank=True, null=True, verbose_name='Дата заведения')),
                ('createown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
